/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type ServiceReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "service";
};

export type PageContent = {
  _id: string;
  _type: "pageContent";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  key?: string;
  featuredServices?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
  heroReviews?: Array<{
    name: string;
    initial?: string;
    text: string;
    _key: string;
  }>;
  principles?: Array<{
    title: string;
    text: string;
    _key: string;
  }>;
  copy?: Array<{
    key?: string;
    label?: string;
    text: string;
    _key: string;
  }>;
};

export type QuoteCategory = {
  _id: string;
  _type: "quoteCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  label: string;
  order?: number;
  enabled?: boolean;
  services?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type LocationReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "location";
};

export type CleaningProject = {
  _id: string;
  _type: "cleaningProject";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  category: string;
  location: string;
  service: string;
  label: string;
  imageUpload?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    caption?: string;
    _type: "image";
  };
  image?: string;
  variant?: "paired" | "single";
  fabric?: string;
  problem?: string;
  treatment?: string;
  result?: string;
  date?: string;
  services?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
  locations?: Array<
    {
      _key: string;
    } & LocationReference
  >;
  order?: number;
  featured?: boolean;
  publicationStatus?: "pending" | "approved" | "withheld";
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  text: string;
  source?: string;
  sourceUrl?: string;
  date?: string;
  rating?: number;
  order?: number;
  featured?: boolean;
  publicationStatus?: "pending" | "approved" | "withheld";
  services?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
  locations?: Array<
    {
      _key: string;
    } & LocationReference
  >;
};

export type Faq = {
  _id: string;
  _type: "faq";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  question: string;
  answer: string;
  order?: number;
  onHomepage?: boolean;
  services?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
  locations?: Array<
    {
      _key: string;
    } & LocationReference
  >;
};

export type FaqReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "faq";
};

export type Location = {
  _id: string;
  _type: "location";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  order?: number;
  status: "active" | "limited" | "not-served";
  pageEnabled?: boolean;
  indexInSearch?: boolean;
  showInFooter?: boolean;
  expanded?: boolean;
  shortDescription: string;
  introduction: string;
  localConsiderations?: string;
  neighbourhoods?: Array<string>;
  mapQuery: string;
  imageUpload?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    caption?: string;
    _type: "image";
  };
  image?: string;
  imageAlt?: string;
  metaTitle?: string;
  metaDescription?: string;
  availableServices?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
  nearbyLocations?: Array<
    {
      _key: string;
    } & LocationReference
  >;
  faq?: Array<{
    question: string;
    answer: string;
    _key: string;
  }>;
  sharedFaqs?: Array<
    {
      _key: string;
    } & FaqReference
  >;
  expandedContent?: {
    heroImage?: string;
    mapImage?: string;
    mapAlt?: string;
    mapLabels?: Array<{
      name: string;
      left?: number;
      top?: number;
      _key: string;
    }>;
    quickBenefits?: Array<{
      icon?: string;
      title: string;
      description: string;
      _key: string;
    }>;
    services?: Array<{
      slug?: string;
      title?: string;
      description?: string;
      imageUpload?: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string;
        caption?: string;
        _type: "image";
      };
      image?: string;
      alt?: string;
      _key: string;
    }>;
    resultExamples?: Array<{
      category?: string;
      title?: string;
      description?: string;
      imageUpload?: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string;
        caption?: string;
        _type: "image";
      };
      image?: string;
      alt?: string;
      _key: string;
    }>;
    processSteps?: Array<{
      icon?: string;
      title: string;
      description: string;
      _key: string;
    }>;
    localAdvantages?: Array<{
      icon?: string;
      title: string;
      description: string;
      _key: string;
    }>;
    mississaugaFaqs?: Array<{
      question: string;
      answer: string;
      _key: string;
    }>;
    copy?: Array<{
      key?: string;
      label?: string;
      text: string;
      _key: string;
    }>;
  };
};

export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  menuLabel: string;
  shortName: string;
  order?: number;
  pageEnabled?: boolean;
  showInNavigation?: boolean;
  featured?: boolean;
  metaTitle: string;
  metaDescription: string;
  heroTitle: string;
  heroDescription: string;
  summary: string;
  imageUpload?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    caption?: string;
    _type: "image";
  };
  image?: string;
  imageAlt: string;
  serviceType?: Array<string>;
  heroProofs?: Array<string>;
  concerns?: Array<string>;
  included?: Array<string>;
  process?: Array<{
    title: string;
    description: string;
    _key: string;
  }>;
  drying: string;
  limitations: string;
  faq?: Array<{
    question: string;
    answer: string;
    _key: string;
  }>;
  sharedFaqs?: Array<
    {
      _key: string;
    } & FaqReference
  >;
  relatedServices?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
  includedHeading?: string;
  processHeading?: string;
  afterCareEyebrow?: string;
  afterCareHeading?: string;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  alternateName: string;
  phone: string;
  displayPhone: string;
  email: string;
  googleProfileUrl: string;
  instagramUrl: string;
  facebookUrl: string;
  region: string;
  languages?: Array<string>;
  areasServed?: Array<string>;
  quoteLabel: string;
  reviewScore?: string;
  reviewCheckedAt?: string;
  defaultTitle: string;
  defaultDescription: string;
  url?: string;
  logo?: string;
  heroImage?: string;
  openingHours?: Array<{
    days: string;
    hours: string;
    _key: string;
  }>;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  excerpt: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    localPath?: string;
    width?: number;
    height?: number;
    alt: string;
    caption?: string;
    _type: "image";
  };
  showCover?: boolean;
  seoTitle?: string;
  relatedServices?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
  publishedAt: string;
  author?: AuthorReference;
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        localPath?: string;
        width?: number;
        height?: number;
        alt: string;
        caption?: string;
        _type: "image";
        _key: string;
      }
  >;
  seoDescription?: string;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | ServiceReference
  | PageContent
  | QuoteCategory
  | SanityImageAssetReference
  | LocationReference
  | CleaningProject
  | SanityImageCrop
  | SanityImageHotspot
  | Testimonial
  | Faq
  | FaqReference
  | Location
  | Service
  | Slug
  | SiteSettings
  | Category
  | AuthorReference
  | CategoryReference
  | Post
  | Author
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../src/sanity/queries.ts
// Variable: websiteContentQuery
// Query: *[_type in ["siteSettings","service","location","faq","testimonial","cleaningProject","quoteCategory","pageContent","post","author","category"]] | order(_id asc)
export type WebsiteContentQueryResult = Array<
  | {
      _id: string;
      _type: "author";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      name: string;
    }
  | {
      _id: string;
      _type: "category";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      title: string;
    }
  | {
      _id: string;
      _type: "cleaningProject";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      title: string;
      category: string;
      location: string;
      service: string;
      label: string;
      imageUpload?: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string;
        caption?: string;
        _type: "image";
      };
      image?: string;
      variant?: "paired" | "single";
      fabric?: string;
      problem?: string;
      treatment?: string;
      result?: string;
      date?: string;
      services?: Array<
        {
          _key: string;
        } & ServiceReference
      >;
      locations?: Array<
        {
          _key: string;
        } & LocationReference
      >;
      order?: number;
      featured?: boolean;
      publicationStatus?: "approved" | "pending" | "withheld";
    }
  | {
      _id: string;
      _type: "faq";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      question: string;
      answer: string;
      order?: number;
      onHomepage?: boolean;
      services?: Array<
        {
          _key: string;
        } & ServiceReference
      >;
      locations?: Array<
        {
          _key: string;
        } & LocationReference
      >;
    }
  | {
      _id: string;
      _type: "location";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      name: string;
      slug: Slug;
      order?: number;
      status: "active" | "limited" | "not-served";
      pageEnabled?: boolean;
      indexInSearch?: boolean;
      showInFooter?: boolean;
      expanded?: boolean;
      shortDescription: string;
      introduction: string;
      localConsiderations?: string;
      neighbourhoods?: Array<string>;
      mapQuery: string;
      imageUpload?: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string;
        caption?: string;
        _type: "image";
      };
      image?: string;
      imageAlt?: string;
      metaTitle?: string;
      metaDescription?: string;
      availableServices?: Array<
        {
          _key: string;
        } & ServiceReference
      >;
      nearbyLocations?: Array<
        {
          _key: string;
        } & LocationReference
      >;
      faq?: Array<{
        question: string;
        answer: string;
        _key: string;
      }>;
      sharedFaqs?: Array<
        {
          _key: string;
        } & FaqReference
      >;
      expandedContent?: {
        heroImage?: string;
        mapImage?: string;
        mapAlt?: string;
        mapLabels?: Array<{
          name: string;
          left?: number;
          top?: number;
          _key: string;
        }>;
        quickBenefits?: Array<{
          icon?: string;
          title: string;
          description: string;
          _key: string;
        }>;
        services?: Array<{
          slug?: string;
          title?: string;
          description?: string;
          imageUpload?: {
            asset?: SanityImageAssetReference;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            alt: string;
            caption?: string;
            _type: "image";
          };
          image?: string;
          alt?: string;
          _key: string;
        }>;
        resultExamples?: Array<{
          category?: string;
          title?: string;
          description?: string;
          imageUpload?: {
            asset?: SanityImageAssetReference;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            alt: string;
            caption?: string;
            _type: "image";
          };
          image?: string;
          alt?: string;
          _key: string;
        }>;
        processSteps?: Array<{
          icon?: string;
          title: string;
          description: string;
          _key: string;
        }>;
        localAdvantages?: Array<{
          icon?: string;
          title: string;
          description: string;
          _key: string;
        }>;
        mississaugaFaqs?: Array<{
          question: string;
          answer: string;
          _key: string;
        }>;
        copy?: Array<{
          key?: string;
          label?: string;
          text: string;
          _key: string;
        }>;
      };
    }
  | {
      _id: string;
      _type: "pageContent";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      title: string;
      key?: string;
      featuredServices?: Array<
        {
          _key: string;
        } & ServiceReference
      >;
      heroReviews?: Array<{
        name: string;
        initial?: string;
        text: string;
        _key: string;
      }>;
      principles?: Array<{
        title: string;
        text: string;
        _key: string;
      }>;
      copy?: Array<{
        key?: string;
        label?: string;
        text: string;
        _key: string;
      }>;
    }
  | {
      _id: string;
      _type: "post";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      title: string;
      slug: Slug;
      excerpt: string;
      coverImage?: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        localPath?: string;
        width?: number;
        height?: number;
        alt: string;
        caption?: string;
        _type: "image";
      };
      showCover?: boolean;
      seoTitle?: string;
      relatedServices?: Array<
        {
          _key: string;
        } & ServiceReference
      >;
      publishedAt: string;
      author?: AuthorReference;
      categories?: Array<
        {
          _key: string;
        } & CategoryReference
      >;
      body: Array<
        | {
            children?: Array<{
              marks?: Array<string>;
              text?: string;
              _type: "span";
              _key: string;
            }>;
            style?: "blockquote" | "h2" | "h3" | "normal";
            listItem?: "bullet" | "number";
            markDefs?: Array<{
              href: string;
              _type: "link";
              _key: string;
            }>;
            level?: number;
            _type: "block";
            _key: string;
          }
        | {
            asset?: SanityImageAssetReference;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            localPath?: string;
            width?: number;
            height?: number;
            alt: string;
            caption?: string;
            _type: "image";
            _key: string;
          }
      >;
      seoDescription?: string;
    }
  | {
      _id: string;
      _type: "quoteCategory";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      label: string;
      order?: number;
      enabled?: boolean;
      services?: Array<
        {
          _key: string;
        } & ServiceReference
      >;
    }
  | {
      _id: string;
      _type: "service";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      name: string;
      slug: Slug;
      menuLabel: string;
      shortName: string;
      order?: number;
      pageEnabled?: boolean;
      showInNavigation?: boolean;
      featured?: boolean;
      metaTitle: string;
      metaDescription: string;
      heroTitle: string;
      heroDescription: string;
      summary: string;
      imageUpload?: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string;
        caption?: string;
        _type: "image";
      };
      image?: string;
      imageAlt: string;
      serviceType?: Array<string>;
      heroProofs?: Array<string>;
      concerns?: Array<string>;
      included?: Array<string>;
      process?: Array<{
        title: string;
        description: string;
        _key: string;
      }>;
      drying: string;
      limitations: string;
      faq?: Array<{
        question: string;
        answer: string;
        _key: string;
      }>;
      sharedFaqs?: Array<
        {
          _key: string;
        } & FaqReference
      >;
      relatedServices?: Array<
        {
          _key: string;
        } & ServiceReference
      >;
      includedHeading?: string;
      processHeading?: string;
      afterCareEyebrow?: string;
      afterCareHeading?: string;
    }
  | {
      _id: string;
      _type: "siteSettings";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      name: string;
      alternateName: string;
      phone: string;
      displayPhone: string;
      email: string;
      googleProfileUrl: string;
      instagramUrl: string;
      facebookUrl: string;
      region: string;
      languages?: Array<string>;
      areasServed?: Array<string>;
      quoteLabel: string;
      reviewScore?: string;
      reviewCheckedAt?: string;
      defaultTitle: string;
      defaultDescription: string;
      url?: string;
      logo?: string;
      heroImage?: string;
      openingHours?: Array<{
        days: string;
        hours: string;
        _key: string;
      }>;
    }
  | {
      _id: string;
      _type: "testimonial";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      name: string;
      text: string;
      source?: string;
      sourceUrl?: string;
      date?: string;
      rating?: number;
      order?: number;
      featured?: boolean;
      publicationStatus?: "approved" | "pending" | "withheld";
      services?: Array<
        {
          _key: string;
        } & ServiceReference
      >;
      locations?: Array<
        {
          _key: string;
        } & LocationReference
      >;
    }
>;

// Query TypeMap
declare global {
  interface SanityQueries {
    '*[_type in ["siteSettings","service","location","faq","testimonial","cleaningProject","quoteCategory","pageContent","post","author","category"]] | order(_id asc)': WebsiteContentQueryResult;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
